---
# "Client Report - ["What's in a Name?"]"
## 

format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
```

# What's in a name?

## Elevator pitch

_Bible names have seen many twists and turns and any have fallen out of popularity compared to that of the 60s and 70s. This may be attributed to varying parenting styles or changes in culture as religion has began to fall out of the mainstream. Very few consider themselves reilgious or practicing, thus the downwards trend in use for most names_

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
df = pd.read_csv("https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv")
```

__Questions and Tasks__

## QUESTION|TASK 1

__1. How does your name at your birth year compare to its use historically?__

_The number of people named Josh was post-slump following the 70s. The 60s and 70s saw a huge spike in use, but was followed by a sharp drop in the 80s and 90s. Nearing 2015 is one of the lowest points since the 40s. I was born in 1999 which was near a drop. According to data from [Statista] https://www.statista.com/statistics/245478/self-described-religious-identification-of-americans/ Protestant and Catholic populations have declined steadily since the 70s, leading to now where 22% of the population don't consider themselves religious._

```{python}
print('The number of people in 1999 with the name Josh:')
josh = df.query('name == "Josh"')
josh.query('year == 1999')
fig = px.line(josh, 
  x='year' , 
  y='Total', 
  title='The Rise and Fall of Josh',
  markers= True
)
fig.add_shape(
  type = 'line',
  line_color = 'red',
  line_width = 2,
  opacity = 1,
  line_dash = 'dot',
  x0=0,
  x1=1,
  xref='paper',
  y0 = 130,
  y1 = 130,
  yref = 'y'
)
fig.add_annotation(
  text = 'My Birthday line',
  x=1950,
  y=140,
  arrowhead=1,
  showarrow=True
)
fig.show()
```

## QUESTION|TASK 2

__2. If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_The name Brittany was extremely common in the 90s. My guess is that a Brittany is most likely in their 30s or 40s. It's also a coincidence that my mother is named Brittany which helps give me a gauge on where it lies. Most likely they aren't in their 20s considering the usage rates are almost as low as the 70s._

```{python}
#| label: Q2
#| code-summary: Query the data to show only Brittany
brittany = df.query('name == "Brittany"')
fig = px.bar(brittany, x='year', y='Total', title='How old is Brittany?')
brittany.mean()

fig.show()
```


## QUESTION|TASK 3

__3. Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?__

_Mary was the most common of the four, considering that the name is short and sweet. This can possibly be attributed to Mary being the mother of Jesus, which carries heavy weight in the protestant and catholic religions, the biggest and most popular on Earth. All have seen a decline but none as much as Mary who saw an 18% decrease in only 20 years._

```{python}
#| label: Q3
#| code-summary: Filter to show names only and date ranges. Graph to show data.
name_list = ['Mary' , 'Martha' , 'Peter' , 'Paul']
gb = df.query('name in @name_list')
fig = px.line(
  gb, 
  x = 'year',
  y = 'Total',
  title = 'Where are Mary, Marth, Peter, and Paul?',
  color = 'name'
)
fig.show()




```
