---
title: "Client Report - Missing Data and Late Flights"
subtitle: "Course DS 250"
author: "Josh Deere"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import numpy as np
import plotly.express as px
```


## Elevator pitch

_A SHORT (4-5 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._

```{python}
flights = pd.read_json("https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json")
```

__Questions and Tasks__

## QUESTION|TASK 1

__Fix all of the varied missing data types in the data to be consistent (all missing values should be displayed as “NaN”).__

_There were several months that were written as "n/a." To maintain data integrity, those needed to be replaced with month names. Airport names were missing but included the airport code which helped with filling in the blanks. There were other numbers that were too high or irregular in pattern which needed to be fixed._

```{python}
#| label: Q1
#| code-summary: Read and format data

flights.month.replace(['NaN','n/a'],np.nan,inplace = True)
flights.month.replace('Febuary','February',inplace= True)
late_mean = flights.num_of_delays_late_aircraft.mean(skipna= True)
flights.num_of_delays_late_aircraft.replace(-999,late_mean,inplace = True)
flights.num_of_delays_carrier.replace('1500+',1500,inplace= True)
flights.airport_name.replace('','Washington, DC: Washington Dulles International',inplace= True)
flights["month"] = flights["month"].ffill()
flights.to_json()
```

## QUESTION|TASK 2

__Which airport has the worst delays?__

_Security checkpoints and carrier efficiency indicate how well an airport can accomodate the traffic and get people on flights. I chose these because I feel that the other variables can have extrinsic factors outside of the airport's hands. Salt Lake International experiences many delays through security and some of the flights have VERY long delays as well. With the airport expansion underway, this is clearly affecting their efficiency in getting people in and out._

```{python}
#| label: Security
# Choose which columns to use for metric 
flights['total_delays_perc'] = flights['num_of_delays_total'] / flights['num_of_flights_total']
flights
# I want to display percentage from the chosen columns in a table by airport code
px.bar(flights,x='airport_code',y= 'total_delays_perc',color= 'month')
# airport code - columns used for calculations - percentage
summary = flights[['airport_code','num_of_flights_total' , 'num_of_delays_total','total_delays_perc']]
summary

```

## QUESTION|TASK 3

__What is the best month to fly if you want to avoid delays of any length?__

_The best month to fly out of an airport is September. This month features the least amount of delays. This month is right before the holidays when people put their heads down and save up for the end of the year. The bars are also stacked by airport so you can also see which airport has the least amount of delays and when if you need to pick the nearest international airport._

```{python}
#| label: Q3
#| code-summary: Read and format data
# Create sum for September and November
months = flights.groupby('month')
least = totals.num_of_delays_total.sum().min()
# Make graph
graph = px.bar(flights, x= 'month', 
y= 'num_of_delays_total', 
color= 'month', 
title= "Hopefully Your Plane Doesn't FALL Out of The Sky"
)
# Label least amount
graph.add_annotation(text= '206,223',
x= 'September', 
y= least
)
# Label 2nd least
graph.add_annotation(text= '209,559',
x= 'November', 
y= 209559
)
```

## QUESTION|TASK 4

__"...create a new column that calculates the total number of flights delayed by weather (both severe and mild)"__

```{python}
'''100% of delayed flights in the Weather category are due to weather. 
30% of all delayed flights in the Late-Arriving category are due to weather.
From April to August, 40% of delayed flights in the NAS category are due to weather. The rest of the months, the proportion rises to 65%.
'''
# Late Arriving
flights['aircraft_weather_delays'] = flights['num_of_delays_late_aircraft'].multiply(0.3).round(0)
# Apr - Aug flights
flights['nas_april_to_august'] = flights['num_of_delays_nas'].filter(items= ['April','May','June','July','August']).multiply(0.4).round(0) 
# Rest of year
flights['nas_rest'] = flights['num_of_delays_nas'].filter(items= ['January','February','March','September','October','November','December']).multiply(0.65).round(0)


```


## QUESTION|TASK 5

__Using the new weather variable calculated above, create a barplot showing the proportion of all flights that are delayed by weather at each airport. Discuss what you learn from this graph.__

