---
layout: cv
title: Josh Deere's CV
---
# Josh Deere
Student

<div id="webaddress">
<a href="deerejoshm@gmail.com">deerejoshm@gmail.com</a>
| <a href="https://www.linkedin.com/in/deere-joshua/">My LinkedIn</a>
</div>

## Education

`2020-2025`
Brigham Young University-Idaho, Business Analytics

Related Courses: Managerial Accounting, Spreadsheet Analysis for Business, Programming With Functions, Business Analytics, Financial Management, Business Statistics, Data Science Programming, Database Design and Development, Business Intelligence and Analysis

## Employment

`April 2023-Sep 2023`
__BYU-I__, *Project Coordinator*, Rexburg, ID

- Promoted to Coordinator in less than 14 weeks after starting position
- Directed a team of students in accomplishing grounds-keeping tasks in 4 hour increments
- Offered assistance each week to other teams to complete advanced and complicated projects as coordinator for both groups
- Performed physically strenuous tasks for long hours both in a team and solo environment such as heavy equipment operation and        maintenance
- Coordinated with Supervisor Lead to plan weekly agenda and projects requiring immediate attention

`May 2022-Aug 2022`
__Mountain America Credit Union__, *Member Experience Officer*, Idaho Falls, ID

- Organized branch data and loan volume in Excel to improve performance metrics in branch
- Prepared and processed personal and business loan documents in Word for colleagues after only one week of training
- Rescued up to $100k in predatory loans in auto, credit card, and personal loan market after only 3 months
- Finalized all loan applications on day of credit pull or within one week of loan request
- Completed all loan applications with little or no compliance errors after only 1 month of working

`April 2021-Sep 2021`
__Chick-fil-a__, *Team Lead*, Colorado Springs, CO

- Trained for leadership position within 2 months of training while advancing productivity by 15%
- Learned and mastered all positions in less than two months
- Implemented new employee performance metric and customer outreach program with owner after only 1 month

## Involvement and Activities

- Jazz ensemble Lead drummer
- Various physical pursuits such as Football and Bodybuilding
- Served as a missionary for 2 years in South America as a leader of up to twelve American and Foreign colleagues
- Door to door sales and marketing experience
- Competed in conference championships for Shotput in 1st season

## Skills

- Power BI, Excel, Tableau, MySQL, Python, Word, PowerPoint, Outlook
- Fluent in Spanish and Intermediate in Portuguese
- Quick to retain information and training to ensure smooth transition to new positions
- Flexible and dedicated ensuring proper care and attention to every detail
- Willing to receive criticism and assistance to learn new ways to solve issues or needs dependent on each situation
- Dependable and hardworking. Not afraid to go any number of extra miles in any situation
- Worthy leader and communicator willing to assist with conflict resolution


<!-- ### Footer

Last updated: May 2013 -->